# Generated by Django 3.1.5 on 2021-02-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(default='', max_length=20400)),
                ('time', models.CharField(default='', max_length=500)),
                ('ip', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('songid', models.IntegerField(default=-1)),
                ('albummid', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=200)),
                ('author', models.CharField(default='', max_length=200)),
                ('album', models.CharField(default='', max_length=100)),
                ('lyric', models.CharField(default='', max_length=1000)),
                ('time', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
